//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5App.PL.CountryService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CountryService.ICountryService")]
    public interface ICountryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICountryService/GetListOfCountryNamesByCode", ReplyAction="http://tempuri.org/ICountryService/GetListOfCountryNamesByCodeResponse")]
        MVC5App.Core.DTOs.Concrete.CountryListDto[] GetListOfCountryNamesByCode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICountryService/GetListOfCountryNamesByCode", ReplyAction="http://tempuri.org/ICountryService/GetListOfCountryNamesByCodeResponse")]
        System.Threading.Tasks.Task<MVC5App.Core.DTOs.Concrete.CountryListDto[]> GetListOfCountryNamesByCodeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICountryService/AddCountry", ReplyAction="http://tempuri.org/ICountryService/AddCountryResponse")]
        void AddCountry(MVC5App.Core.DTOs.Concrete.CountryAddDto countryAddDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICountryService/AddCountry", ReplyAction="http://tempuri.org/ICountryService/AddCountryResponse")]
        System.Threading.Tasks.Task AddCountryAsync(MVC5App.Core.DTOs.Concrete.CountryAddDto countryAddDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICountryService/GetCountryInfoByName", ReplyAction="http://tempuri.org/ICountryService/GetCountryInfoByNameResponse")]
        MVC5App.Core.DTOs.Concrete.CountryInfoByServiceDto GetCountryInfoByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICountryService/GetCountryInfoByName", ReplyAction="http://tempuri.org/ICountryService/GetCountryInfoByNameResponse")]
        System.Threading.Tasks.Task<MVC5App.Core.DTOs.Concrete.CountryInfoByServiceDto> GetCountryInfoByNameAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICountryServiceChannel : MVC5App.PL.CountryService.ICountryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CountryServiceClient : System.ServiceModel.ClientBase<MVC5App.PL.CountryService.ICountryService>, MVC5App.PL.CountryService.ICountryService {
        
        public CountryServiceClient() {
        }
        
        public CountryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CountryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CountryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CountryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MVC5App.Core.DTOs.Concrete.CountryListDto[] GetListOfCountryNamesByCode() {
            return base.Channel.GetListOfCountryNamesByCode();
        }
        
        public System.Threading.Tasks.Task<MVC5App.Core.DTOs.Concrete.CountryListDto[]> GetListOfCountryNamesByCodeAsync() {
            return base.Channel.GetListOfCountryNamesByCodeAsync();
        }
        
        public void AddCountry(MVC5App.Core.DTOs.Concrete.CountryAddDto countryAddDto) {
            base.Channel.AddCountry(countryAddDto);
        }
        
        public System.Threading.Tasks.Task AddCountryAsync(MVC5App.Core.DTOs.Concrete.CountryAddDto countryAddDto) {
            return base.Channel.AddCountryAsync(countryAddDto);
        }
        
        public MVC5App.Core.DTOs.Concrete.CountryInfoByServiceDto GetCountryInfoByName(string name) {
            return base.Channel.GetCountryInfoByName(name);
        }
        
        public System.Threading.Tasks.Task<MVC5App.Core.DTOs.Concrete.CountryInfoByServiceDto> GetCountryInfoByNameAsync(string name) {
            return base.Channel.GetCountryInfoByNameAsync(name);
        }
    }
}
